### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Samtjs** [blueedgetechno/win11React#724] opened 2023-01-10 02:24 UTC
### What happened?

A bug happened!
I can't access win11.blueedge.me

### To reproduce the behavior?

reproduce!

### What browser are you seeing the problem on?

Other Browser

**Comment by yashash-pugalia** [comment] 2023-01-10 08:55
Duplicate of #725

**Closed by yashash-pugalia** 2023-01-10 08:55 UTC
Labels: bug
