### ISSUE TITLE
The option to change username and profile picture

### ISSUE THREAD

**Issue by blgoreuxe** [blueedgetechno/win11React#424] opened 2022-04-25 15:25 UTC
I think that it will be a really cool feature in the settings app to change the username to a custom choice instead of just Blue Edge, and then a custom profile picture from a url or from your local files.

**Comment by glitch128** [comment] 2022-04-25 16:21
yes. please do this

**Comment by zero90002** [comment] 2022-04-25 16:28
heck
ye

**Comment by yashash1511** [comment] 2022-04-25 18:41
Duplicate of #374

**Closed by yashash1511** 2022-04-25 18:41 UTC

**Comment by yashash1511** [comment] 2022-04-25 20:27
Duplicate of #301
